version: '3.9'
name: widitrade-senen
services:
  nginx:
    image: nginx:latest
    ports:
      - "8099:80"
    volumes: 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    networks:
      - app_network
    depends_on:
      - php
    environment:
      - TZ=UTC

  php:
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network
    environment:
      - TZ=UTC

networks:
  app_network:
    driver: bridge
